# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c0d4fbcd43209fbe324255c23e4fbeee8b6e08fd2cc3411067885e07e1a344b6fe156137a0df7cb675bc1d86a366305fe6542b151cb14141ff1d2ddc4b6b8f

test:
  secret_key_base: dc229115a84e00de51c8f4bee44d803f6bd725d16d94285d441d3ce4317667a9e9f59c3ccfd282f7598fb0858d3935b76c331d2c3e310f9563f569f9336b533b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
